import { Router } from 'express';
import { getAdmins, getAssignedStores, listBranches, listChains, patchAdmin, patchBranch, patchChain, postAdmin, postBranch, postChain } from '../controllers/organization.controller.js';
import { getManagers, getVendors, patchManager, patchVendor, postManager, postVendor, postVendorLink } from '../controllers/staff.controller.js';
import { getDevice, getDevices, patchDevice, postDevice, postDiagnosticImport, postMediaComplete, postMediaDownload, postMediaSign, putInspection } from '../controllers/device.controller.js';
import { getCatalog } from '../controllers/catalog.controller.js';
import { getMyWallet, getVendorWallet, getWallets, postWalletCredit, postWalletRelease, postWalletReserve } from '../controllers/wallet.controller.js';
import { getAuction, getAuctionBids, getAuctions, getBid, getDeal, getDeals, getMyBids, getSettings, patchSettings, postAuctionAccept, postAuctionBid, postAuctionCancel, postAuctionDecline, postAuctionRebid, postAuctionTick, postDealOtp, postDealPickup, postDealVerify, postDeviceAuction } from '../controllers/auction.controller.js';
import { getPayment, getPayments, postPaymentReconcile, postPaymentRetry } from '../controllers/payout.controller.js';
import { getCustomerRewards, getRedemption, getRedemptions, getRewardOverview, getRewardPolicy, postRedemption, postRedemptionConfirm, postRedemptionOtp, postRewardPolicy } from '../controllers/reward.controller.js';
import { getNotificationHistory, getNotifications, postBroadcast, postNotificationRead } from '../controllers/notification.controller.js';
import { getTicket, getTickets, postTicket, postTicketAssign, postTicketAttachmentComplete, postTicketAttachmentDownload, postTicketAttachmentSign, postTicketNote, postTicketStatus } from '../controllers/support.controller.js';
import { getAudit, getOverview, getPerformance, getReports, postReportExport } from '../controllers/oversight.controller.js';
import { getWalletRecharge, postWalletRecharge, postWalletRechargeAck } from '../controllers/recharge.controller.js';
import { requireAuthentication } from '../middlewares/auth.middleware.js';
import { requireRoles } from '../middlewares/authorize.middleware.js';

const guard = (...roles) => [requireAuthentication, requireRoles(...roles)];

export const organizationRouter = Router();
organizationRouter.get('/chains', ...guard('super_admin', 'admin'), listChains);
organizationRouter.post('/chains', ...guard('super_admin'), postChain);
organizationRouter.patch('/chains/:id', ...guard('super_admin'), patchChain);
organizationRouter.get('/branches', ...guard('super_admin', 'admin'), listBranches);
organizationRouter.post('/branches', ...guard('super_admin'), postBranch);
organizationRouter.patch('/branches/:id', ...guard('super_admin', 'admin'), patchBranch);
organizationRouter.get('/admins', ...guard('super_admin'), getAdmins);
organizationRouter.post('/admins', ...guard('super_admin'), postAdmin);
organizationRouter.patch('/admins/:id', ...guard('super_admin'), patchAdmin);
organizationRouter.get('/managers', ...guard('super_admin', 'admin'), getManagers);
organizationRouter.post('/managers', ...guard('super_admin', 'admin'), postManager);
organizationRouter.patch('/managers/:id', ...guard('super_admin', 'admin'), patchManager);
organizationRouter.get('/vendors', ...guard('super_admin', 'admin'), getVendors);
organizationRouter.post('/vendors', ...guard('super_admin', 'admin'), postVendor);
organizationRouter.post('/vendors/links', ...guard('super_admin', 'admin'), postVendorLink);
organizationRouter.patch('/vendors/:id', ...guard('super_admin', 'admin'), patchVendor);

export const operationsRouter = Router();
operationsRouter.get('/catalog', getCatalog);
operationsRouter.get('/assigned-stores', ...guard('vendor'), getAssignedStores);
operationsRouter.get('/devices', ...guard('super_admin', 'admin', 'store_manager', 'vendor'), getDevices);
operationsRouter.post('/devices', ...guard('store_manager', 'super_admin'), postDevice);
operationsRouter.get('/devices/:id', ...guard('super_admin', 'admin', 'store_manager', 'vendor'), getDevice);
operationsRouter.patch('/devices/:id', ...guard('store_manager', 'super_admin'), patchDevice);
operationsRouter.put('/devices/:id/inspection', ...guard('store_manager', 'super_admin'), putInspection);
operationsRouter.post('/devices/:id/media/sign', ...guard('store_manager', 'super_admin'), postMediaSign);
operationsRouter.post('/devices/:id/media/complete', ...guard('store_manager', 'super_admin'), postMediaComplete);
operationsRouter.post('/devices/:id/media/download', ...guard('super_admin', 'admin', 'store_manager', 'vendor'), postMediaDownload);
operationsRouter.post('/diagnostic-imports', ...guard('store_manager', 'super_admin'), postDiagnosticImport);
operationsRouter.get('/wallets/me', ...guard('vendor'), getMyWallet);
operationsRouter.get('/wallets', ...guard('super_admin'), getWallets);
operationsRouter.get('/wallets/:vendorId', ...guard('super_admin', 'admin', 'vendor'), getVendorWallet);
operationsRouter.post('/wallets/:vendorId/credits', ...guard('super_admin'), postWalletCredit);
operationsRouter.post('/wallets/reservations', ...guard('super_admin', 'vendor'), postWalletReserve);
operationsRouter.post('/wallets/releases', ...guard('super_admin', 'vendor'), postWalletRelease);
operationsRouter.post('/wallets/recharges', ...guard('vendor'), postWalletRecharge);
operationsRouter.get('/wallets/recharges/:id', ...guard('vendor', 'super_admin'), getWalletRecharge);
operationsRouter.post('/wallets/recharges/:id/acknowledge', ...guard('vendor'), postWalletRechargeAck);
operationsRouter.get('/settings', ...guard('super_admin', 'admin', 'store_manager'), getSettings);
operationsRouter.patch('/settings', ...guard('super_admin'), patchSettings);
operationsRouter.post('/auctions/tick', ...guard('super_admin', 'admin', 'store_manager'), postAuctionTick);
operationsRouter.get('/auctions', ...guard('super_admin', 'admin', 'store_manager', 'vendor'), getAuctions);
operationsRouter.get('/auctions/:id', ...guard('super_admin', 'admin', 'store_manager', 'vendor'), getAuction);
operationsRouter.get('/auctions/:id/bids', ...guard('super_admin', 'admin', 'store_manager'), getAuctionBids);
operationsRouter.post('/auctions/:id/cancel', ...guard('store_manager', 'super_admin'), postAuctionCancel);
operationsRouter.post('/auctions/:id/decline', ...guard('store_manager', 'super_admin'), postAuctionDecline);
operationsRouter.post('/auctions/:id/rebid', ...guard('store_manager', 'super_admin'), postAuctionRebid);
operationsRouter.post('/auctions/:id/accept', ...guard('store_manager', 'super_admin'), postAuctionAccept);
operationsRouter.get('/deals', ...guard('super_admin', 'admin', 'store_manager', 'vendor'), getDeals);
operationsRouter.get('/deals/:id', ...guard('super_admin', 'admin', 'store_manager', 'vendor'), getDeal);
operationsRouter.post('/deals/:id/otp', ...guard('store_manager', 'super_admin'), postDealOtp);
operationsRouter.post('/deals/:id/verify', ...guard('store_manager', 'super_admin'), postDealVerify);
operationsRouter.post('/deals/:id/pickup', ...guard('store_manager', 'super_admin'), postDealPickup);
operationsRouter.get('/payments', ...guard('super_admin', 'admin', 'store_manager'), getPayments);
operationsRouter.get('/payments/:id', ...guard('super_admin', 'admin', 'store_manager'), getPayment);
operationsRouter.post('/payments/:id/retry', ...guard('super_admin', 'admin', 'store_manager'), postPaymentRetry);
operationsRouter.post('/payments/:id/reconcile', ...guard('super_admin', 'admin'), postPaymentReconcile);
operationsRouter.get('/rewards/overview', ...guard('super_admin', 'admin', 'store_manager'), getRewardOverview);
operationsRouter.get('/rewards/policy', ...guard('super_admin', 'admin', 'store_manager'), getRewardPolicy);
operationsRouter.post('/rewards/policy', ...guard('super_admin'), postRewardPolicy);
operationsRouter.get('/rewards/customers/:phone', ...guard('super_admin', 'admin', 'store_manager'), getCustomerRewards);
operationsRouter.get('/rewards/redemptions', ...guard('super_admin', 'admin', 'store_manager'), getRedemptions);
operationsRouter.post('/rewards/redemptions', ...guard('store_manager', 'super_admin'), postRedemption);
operationsRouter.get('/rewards/redemptions/:id', ...guard('super_admin', 'admin', 'store_manager'), getRedemption);
operationsRouter.post('/rewards/redemptions/:id/otp', ...guard('store_manager', 'super_admin'), postRedemptionOtp);
operationsRouter.post('/rewards/redemptions/:id/confirm', ...guard('store_manager', 'super_admin'), postRedemptionConfirm);
operationsRouter.get('/notifications', ...guard('super_admin', 'admin', 'store_manager', 'vendor'), getNotifications);
operationsRouter.get('/notifications/history', ...guard('super_admin', 'admin'), getNotificationHistory);
operationsRouter.post('/notifications/broadcasts', ...guard('super_admin', 'admin'), postBroadcast);
operationsRouter.post('/notifications/:id/read', ...guard('super_admin', 'admin', 'store_manager', 'vendor'), postNotificationRead);
operationsRouter.get('/tickets', ...guard('super_admin', 'admin', 'store_manager', 'vendor'), getTickets);
operationsRouter.post('/tickets', ...guard('super_admin', 'admin', 'store_manager', 'vendor'), postTicket);
operationsRouter.post('/tickets/:id/notes', ...guard('super_admin', 'admin', 'store_manager', 'vendor'), postTicketNote);
operationsRouter.post('/tickets/:id/assign', ...guard('super_admin', 'admin'), postTicketAssign);
operationsRouter.post('/tickets/:id/status', ...guard('super_admin', 'admin'), postTicketStatus);
operationsRouter.post('/tickets/:id/attachments/sign', ...guard('store_manager', 'vendor'), postTicketAttachmentSign);
operationsRouter.post('/tickets/:id/attachments/complete', ...guard('store_manager', 'vendor'), postTicketAttachmentComplete);
operationsRouter.post('/tickets/:id/attachments/:attachmentId/download', ...guard('super_admin', 'admin', 'store_manager', 'vendor'), postTicketAttachmentDownload);
operationsRouter.get('/tickets/:id', ...guard('super_admin', 'admin', 'store_manager', 'vendor'), getTicket);
operationsRouter.get('/overview', ...guard('super_admin', 'admin'), getOverview);
operationsRouter.get('/reports', ...guard('super_admin', 'admin'), getReports);
operationsRouter.post('/reports/export', ...guard('super_admin', 'admin'), postReportExport);
operationsRouter.get('/audit', ...guard('super_admin', 'admin'), getAudit);
operationsRouter.get('/performance', ...guard('vendor'), getPerformance);
operationsRouter.post('/auctions/:id/bids', ...guard('vendor'), postAuctionBid);
operationsRouter.get('/bids', ...guard('vendor'), getMyBids);
operationsRouter.get('/bids/:id', ...guard('vendor', 'store_manager', 'super_admin', 'admin'), getBid);
operationsRouter.post('/devices/:id/auctions', ...guard('store_manager', 'super_admin'), postDeviceAuction);
